# Generated by Django 5.2.4 on 2025-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_projectassigneduser_project_assigned_users_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['to_do', 'pending', 'ready', 'in_progress', 'in_review', 'testing'])), name='valid_task_status'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'medium', 'high'])), name='valid_task_priority'),
        ),
        migrations.AddConstraint(
            model_name='taskrelation',
            constraint=models.CheckConstraint(condition=models.Q(('relation_type__in', ['start_to_start', 'start_to_finish', 'finish_to_start', 'finish_to_finish'])), name='valid_relation_type'),
        ),
    ]
