# Generated by Django 5.2.4 on 2025-12-15 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_all_day', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('color__in', ['red', 'blue', 'green', 'orange'])), name='valid_event_color'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='valid_event_date_range')],
            },
        ),
    ]
