# Generated by Django 5.2.4 on 2025-12-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
