# Generated by Django 5.2.4 on 2025-11-21 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_assigned_users'),
        ('tasks', '0002_alter_task_project_alter_projectassigneduser_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__gte', models.F('start_date'))), name='valid_project_dates'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='valid_project_progress'),
        ),
    ]
