# Generated by Django 5.2.4 on 2025-12-02 00:00

from django.db import migrations

def migrate_assigned_users_to_members(apps, schema_editor):
    """Migrate data from assigned_users to members field"""
    Project = apps.get_model('projects', 'Project')
    ProjectAssignedUser = apps.get_model('tasks', 'ProjectAssignedUser')
    
    for project in Project.objects.all():
        # Get all user IDs from assigned_users through table
        assigned_user_ids = ProjectAssignedUser.objects.filter(
            project=project
        ).values_list('user_id', flat=True)
        
        if assigned_user_ids:
            # Add these users to members field
            project.members.add(*assigned_user_ids)

def reverse_migrate_assigned_users_to_members(apps, schema_editor):
    """Reverse migration - this is a no-op since we can't reliably reverse"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_valid_project_dates_and_more'),
        ('tasks', '0002_alter_task_project_alter_projectassigneduser_project_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_assigned_users_to_members,
            reverse_migrate_assigned_users_to_members,
        ),
    ]