# Generated by Django 5.2.4 on 2025-12-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_migrate_assigned_users_to_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_users',
        ),
    ]