# Generated by Django 5.2.4 on 2025-12-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
