# Generated by Django 5.2.4 on 2025-12-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_project_alter_projectassigneduser_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAssignedUser',
        ),
    ]