# Generated by Django 5.2.4 on 2025-12-03 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_assigned_users'),
        ('tasks', '0003_delete_projectassigneduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='valid_task_status',
        ),
        migrations.RemoveConstraint(
            model_name='taskrelation',
            name='valid_relation_type',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskrelation',
            name='relation_type',
            field=models.CharField(choices=[('FtS', 'Finish to Start'), ('FtF', 'Finish to Finish'), ('StS', 'Start to Start'), ('StF', 'Start to Finish')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['todo', 'in_progress', 'done'])), name='valid_task_status'),
        ),
        migrations.AddConstraint(
            model_name='taskrelation',
            constraint=models.CheckConstraint(condition=models.Q(('relation_type__in', ['FtS', 'FtF', 'StS', 'StF'])), name='valid_relation_type'),
        ),
    ]
